import type { Metadata } from "next";
import { noto_sans } from "@/app/ui/fonts";
import "./globals.css";
import LayoutClient from "./LayoutClient"; // 👈 our client wrapper

export const metadata: Metadata = {
  title: "Oesisu Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${noto_sans.className} antialiased relative h-full w-full`}
      >
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
